"""Fallback job pool used when no job-board connector is configured, so the
app is fully demoable out of the box. These are the same Seattle-area
postings gathered for the original single-user SDE Radar prototype.
"""

from typing import TypedDict


class SeedJob(TypedDict):
    """Shape of a bundled seed posting.

    Typed rather than a bare dict so that mypy can check the conversion to
    RawJob in job_ingestion -- without this, every field reads as `object`
    and type errors at that boundary go undetected.
    """

    external_id: str
    title: str
    company: str
    location: str
    comp_min: float | None
    comp_max: float | None
    comp_unit: str
    job_type: str
    posted: str
    url: str
    description: str


SEED_JOBS: list[SeedJob] = [
    {
        "external_id": "seed-blue-origin-swe3-applied-ai",
        "title": "Software Engineer III – Applied AI",
        "company": "Blue Origin",
        "location": "Seattle, WA",
        "comp_min": 164652,
        "comp_max": 230513,
        "comp_unit": "year",
        "job_type": "Full-time",
        "posted": "2026-05-01",
        "url": "https://to.indeed.com/aach987xyqx2",
        "description": "Lead full-stack development of search, RAG (Retrieval-Augmented Generation), and agentic AI applications using Python, TypeScript/React, and Java. Own retrieval pipeline quality, LLM evaluation frameworks. AWS ECS/EKS, Lambda, OpenSearch, S3, CloudWatch, Terraform/CDK. LangChain, LlamaIndex, AutoGen.",
    },
    {
        "external_id": "seed-snap-backend-l5-ads",
        "title": "Software Engineer, Backend, Level 5 – Ads Delivery",
        "company": "Snap Inc.",
        "location": "Bellevue, WA",
        "comp_min": 178000,
        "comp_max": 313000,
        "comp_unit": "year",
        "job_type": "Full-time",
        "posted": "2026-05-28",
        "url": "https://to.indeed.com/aaqmqyjp2gtr",
        "description": "Design, implement and operate ads delivery infrastructure. Large-scale microservices and distributed systems. Experience with Java, C++, Python. NoSQL, Memcache/Redis, Kubernetes, AWS/GCP services.",
    },
    {
        "external_id": "seed-socure-senior-backend-docv",
        "title": "Senior Software Engineer – Backend (DocV)",
        "company": "Socure",
        "location": "Seattle, WA",
        "comp_min": 180000,
        "comp_max": 200000,
        "comp_unit": "year",
        "job_type": "Full-time",
        "posted": "2026-06-01",
        "url": "https://to.indeed.com/aa2xxw9c82rq",
        "description": "Build scalable backend services and APIs for identity document processing. Java, Go, Scala, gRPC and RESTful APIs. AWS, Docker/Kubernetes, Kafka, Spark.",
    },
    {
        "external_id": "seed-adobe-senior-sde5-express",
        "title": "Senior Software Development Engineer (Adobe Express)",
        "company": "Adobe",
        "location": "Seattle, WA",
        "comp_min": 159200,
        "comp_max": 301600,
        "comp_unit": "year",
        "job_type": "Full-time",
        "posted": "2026-05-12",
        "url": "https://to.indeed.com/aamw2zvsyc8p",
        "description": "Own end-to-end system design across frontend, backend and platform. Agentic workflows leveraging generative AI/LLMs. React, TypeScript, Node.js, microservices. RAG, MCP.",
    },
    {
        "external_id": "seed-readai-senior-fullstack",
        "title": "Senior Software Engineer – Fullstack",
        "company": "Read AI",
        "location": "Seattle, WA",
        "comp_min": 180000,
        "comp_max": 220000,
        "comp_unit": "year",
        "job_type": "Full-time",
        "posted": "2026-04-22",
        "url": "https://to.indeed.com/aafg4dwyxwbs",
        "description": "React and TypeScript frontend, Node.js/Java/Python backend, AWS, SQL and NoSQL. Deploying or integrating LLMs into consumer-facing products.",
    },
    {
        "external_id": "seed-microsoft-agentic-dev-productivity",
        "title": "Senior Software Engineer (AI / Agentic Developer Productivity)",
        "company": "Microsoft",
        "location": "Redmond, WA",
        "comp_min": 119800,
        "comp_max": 261000,
        "comp_unit": "year",
        "job_type": "Full-time",
        "posted": "2026-04-17",
        "url": "https://to.indeed.com/aa7kyzx99yjg",
        "description": "Building an agentic engineering platform. Java, Python, C#. LangChain, Semantic Kernel, AutoGen, LlamaIndex. Agent SDKs, RAG, multi-step reasoning.",
    },
    {
        "external_id": "seed-google-staff-swe-aiml",
        "title": "Staff Software Engineer, AI/ML, Google Cloud AI",
        "company": "Google",
        "location": "Kirkland, WA",
        "comp_min": 207000,
        "comp_max": 301000,
        "comp_unit": "year",
        "job_type": "Full-time",
        "posted": "2026-06-17",
        "url": "https://to.indeed.com/aanrs8ltmn2q",
        "description": "AI/ML infrastructure, distributed systems, cloud computing at scale.",
    },
    {
        "external_id": "seed-globenet-lead-java-aws",
        "title": "Lead Java Software Engineer with AWS",
        "company": "The AES Group (Globenet Consulting)",
        "location": "Bellevue, WA",
        "comp_min": 60,
        "comp_max": 70,
        "comp_unit": "hour",
        "job_type": "Contract",
        "posted": "2026-07-21",
        "url": "https://to.indeed.com/aaxpmnwk8ccj",
        "description": "Cloud-native backend applications using Java, Spring Boot, AWS. Microservices, Kafka, event-driven services, DynamoDB, MongoDB, Terraform, CI/CD.",
    },
    {
        "external_id": "seed-zoox-senior-staff-fs-ops",
        "title": "Senior/Staff Software Engineer – Full Stack Operational Tools",
        "company": "Zoox",
        "location": "Seattle, WA",
        "comp_min": 230000,
        "comp_max": 276000,
        "comp_unit": "year",
        "job_type": "Full-time",
        "posted": "2026-03-02",
        "url": "https://to.indeed.com/aabngq4blwx8",
        "description": "JavaScript/TypeScript, Node.js, HTML/CSS. React, Vue front-end framework experience. Full-stack systems for autonomous vehicle operations.",
    },
    {
        "external_id": "seed-finvari-frontend-fullstack",
        "title": "Frontend / Full-Stack Engineer (Senior or Staff)",
        "company": "Finvari",
        "location": "Seattle, WA",
        "comp_min": 180000,
        "comp_max": 245000,
        "comp_unit": "year",
        "job_type": "Full-time",
        "posted": "2026-08-27",
        "url": "https://to.indeed.com/aaxmwy6q8ggt",
        "description": "React web front-end and React Native mobile, serverless GCP (Node.js/TypeScript) backend.",
    },
    {
        "external_id": "seed-blue-origin-swe3-generic",
        "title": "Software Engineer III (Enterprise Technology)",
        "company": "Blue Origin",
        "location": "Seattle, WA",
        "comp_min": 164652,
        "comp_max": 230513,
        "comp_unit": "year",
        "job_type": "Full-time",
        "posted": "2026-08-03",
        "url": "https://to.indeed.com/aalng8zvy7cm",
        "description": "Enterprise platform engineering on AWS.",
    },
    {
        "external_id": "seed-microsoft-swe-generic",
        "title": "Software Engineer",
        "company": "Microsoft",
        "location": "Redmond, WA",
        "comp_min": 102100,
        "comp_max": 219200,
        "comp_unit": "year",
        "job_type": "Full-time",
        "posted": "2026-07-18",
        "url": "https://to.indeed.com/aa8sjhy2xxt9",
        "description": "General software engineering role, coding languages including C, C++, C#, Java, JavaScript, or Python.",
    },
    {
        "external_id": "seed-cisco-swe-generic",
        "title": "Software Engineer",
        "company": "Cisco",
        "location": "Seattle, WA",
        "comp_min": 149100,
        "comp_max": 282000,
        "comp_unit": "year",
        "job_type": "Full-time",
        "posted": "2026-07-31",
        "url": "https://to.indeed.com/aakdx2jwv6jr",
        "description": "General software engineering role.",
    },
    {
        "external_id": "seed-adobe-sde-generic",
        "title": "Software Development Engineer",
        "company": "Adobe",
        "location": "Seattle, WA",
        "comp_min": 135100,
        "comp_max": 214950,
        "comp_unit": "year",
        "job_type": "Full-time",
        "posted": "2026-08-04",
        "url": "https://to.indeed.com/aaqvxyqv4xtl",
        "description": "Software development engineer role on the Adobe platform.",
    },
    {
        "external_id": "seed-maincode-swe",
        "title": "Software Engineer",
        "company": "MainCode",
        "location": "Seattle, WA",
        "comp_min": 110000,
        "comp_max": 175000,
        "comp_unit": "year",
        "job_type": "Full-time",
        "posted": "2026-07-30",
        "url": "https://to.indeed.com/aamnzkq27g7z",
        "description": "General software engineering role.",
    },
    {
        "external_id": "seed-intrinsic-senior-fullstack",
        "title": "Senior Full Stack Engineer",
        "company": "Intrinsic (Alphabet)",
        "location": "Bellevue, WA",
        "comp_min": 105000,
        "comp_max": 145000,
        "comp_unit": "year",
        "job_type": "Full-time",
        "posted": "2026-08-21",
        "url": "https://to.indeed.com/aaymqwfk68tf",
        "description": "Full stack engineering for robotics software.",
    },
    {
        "external_id": "seed-google-fde-geo-auto",
        "title": "Forward Deployed Engineer, Geo Auto",
        "company": "Google",
        "location": "Seattle, WA",
        "comp_min": 152000,
        "comp_max": 221000,
        "comp_unit": "year",
        "job_type": "Full-time",
        "posted": "2026-08-27",
        "url": "https://to.indeed.com/aaf7lhpbytjq",
        "description": "Technical solutions consulting for automotive partners integrating Google Maps SDKs. Systems design, technical troubleshooting.",
    },
    {
        "external_id": "seed-deloitte-lead-pfde-fsi",
        "title": "Lead Product Forward Deployed Engineer, FSI Signals",
        "company": "Deloitte",
        "location": "Seattle, WA",
        "comp_min": 134500,
        "comp_max": 265100,
        "comp_unit": "year",
        "job_type": "Full-time",
        "posted": "2026-08-26",
        "url": "https://to.indeed.com/aanfn7xsqh6z",
        "description": "Client-facing pre-sales and delivery management for a financial services data product, without needing to write the underlying code.",
    },
    {
        "external_id": "seed-orchard-fde-robotics",
        "title": "Forward Deployed Robotics Engineer",
        "company": "Orchard Robotics",
        "location": "Seattle, WA",
        "comp_min": 135000,
        "comp_max": 175000,
        "comp_unit": "year",
        "job_type": "Full-time",
        "posted": "2026-02-27",
        "url": "https://to.indeed.com/aak8dmpndspj",
        "description": "Field deployment of robotics systems.",
    },
    {
        "external_id": "seed-surgeai-rl-trainer-renton",
        "title": "Senior Software Engineer, Agentic Coding RL Environments (AI Trainer)",
        "company": "Surge AI",
        "location": "Renton, WA",
        "comp_min": 100,
        "comp_max": 150,
        "comp_unit": "hour",
        "job_type": "Part-time",
        "posted": "2026-08-03",
        "url": "https://to.indeed.com/aavrwqcpp6t9",
        "description": "Part-time contract work designing RL environments for agentic coding models.",
    },
    {
        "external_id": "seed-dataannotation-staff-trainer",
        "title": "Staff Software Engineer – AI Trainer",
        "company": "DataAnnotation",
        "location": "Bothell, WA",
        "comp_min": 50,
        "comp_max": 100,
        "comp_unit": "hour",
        "job_type": "Part-time",
        "posted": "2026-06-11",
        "url": "https://to.indeed.com/aalzzls2hm72",
        "description": "Flexible part-time AI training and annotation work.",
    },
    {
        "external_id": "seed-phoenixgroup-datascientist-aieng",
        "title": "Data Scientist / AI Engineer",
        "company": "Phoenix Group of Virginia",
        "location": "Bremerton, WA",
        "comp_min": 155000,
        "comp_max": 165000,
        "comp_unit": "year",
        "job_type": "Full-time",
        "posted": "2026-07-15",
        "url": "https://to.indeed.com/aaj8dnkft62p",
        "description": "Data science and AI/ML modeling role.",
    },
    {
        "external_id": "seed-retaillockbox-jr-fullstack",
        "title": "Jr. Full Stack Software Engineer, Implementation & Support",
        "company": "Retail Lockbox, Inc.",
        "location": "Seattle, WA",
        "comp_min": 35,
        "comp_max": 37,
        "comp_unit": "hour",
        "job_type": "Full-time",
        "posted": "2026-08-14",
        "url": "https://to.indeed.com/aavwgs9ry669",
        "description": "Junior-level implementation and support engineering role.",
    },
]
