"""add user documents and per-application links

Revision ID: 0502cecd2127
Revises: bfbcddf20b75
Create Date: 2026-08-28 16:31:14.838615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0502cecd2127'
down_revision: Union[str, None] = 'bfbcddf20b75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Both new columns on user_job_matches are nullable: an application
    # recorded before this existed simply has no document attached, which is
    # true rather than a value invented to satisfy a constraint.
    op.create_table('user_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_documents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_documents_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_job_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_document_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cover_letter_document_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_match_resume_document', 'user_documents', ['resume_document_id'], ['id']
        )
        batch_op.create_foreign_key(
            'fk_match_cover_letter_document', 'user_documents', ['cover_letter_document_id'], ['id']
        )



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_job_matches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cover_letter_document_id')
        batch_op.drop_column('resume_document_id')

    with op.batch_alter_table('user_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_documents_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_documents_id'))

    op.drop_table('user_documents')
