"""initial schema

Revision ID: 094413d4e88d
Revises: 
Create Date: 2026-08-28 01:30:48.362710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '094413d4e88d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('comp_min', sa.Float(), nullable=True),
    sa.Column('comp_max', sa.Float(), nullable=True),
    sa.Column('comp_unit', sa.String(length=20), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('posted', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('dedup_key', sa.String(length=700), nullable=False),
    sa.Column('company_norm', sa.String(length=255), nullable=False),
    sa.Column('title_norm', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_listings_company_norm'), 'job_listings', ['company_norm'], unique=False)
    op.create_index('ix_job_listings_company_title', 'job_listings', ['company_norm', 'title_norm'], unique=False)
    op.create_index(op.f('ix_job_listings_dedup_key'), 'job_listings', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_job_listings_external_id'), 'job_listings', ['external_id'], unique=True)
    op.create_index(op.f('ix_job_listings_id'), 'job_listings', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('target_city', sa.String(length=255), nullable=False),
    sa.Column('target_titles', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('years_experience', sa.Float(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_resumes_id'), 'resumes', ['id'], unique=False)
    op.create_table('user_job_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('new', 'saved', 'applied', 'interviewing', 'offer', 'rejected', name='statusenum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_listings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_user_job')
    )
    op.create_index(op.f('ix_user_job_matches_id'), 'user_job_matches', ['id'], unique=False)
    op.create_index(op.f('ix_user_job_matches_job_id'), 'user_job_matches', ['job_id'], unique=False)
    op.create_index(op.f('ix_user_job_matches_user_id'), 'user_job_matches', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_job_matches_user_id'), table_name='user_job_matches')
    op.drop_index(op.f('ix_user_job_matches_job_id'), table_name='user_job_matches')
    op.drop_index(op.f('ix_user_job_matches_id'), table_name='user_job_matches')
    op.drop_table('user_job_matches')
    op.drop_index(op.f('ix_resumes_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_job_listings_id'), table_name='job_listings')
    op.drop_index(op.f('ix_job_listings_external_id'), table_name='job_listings')
    op.drop_index(op.f('ix_job_listings_dedup_key'), table_name='job_listings')
    op.drop_index('ix_job_listings_company_title', table_name='job_listings')
    op.drop_index(op.f('ix_job_listings_company_norm'), table_name='job_listings')
    op.drop_table('job_listings')
    # ### end Alembic commands ###
