"""replace target_city with target_cities

Revision ID: f58a83207162
Revises: dc505eab741c
Create Date: 2026-08-28 15:24:50.676775

"""
from typing import Sequence, Union

from alembic import op
import json

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f58a83207162'
down_revision: Union[str, None] = 'dc505eab741c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Move each user's single city into a list, then drop the old column.

    Written by hand rather than autogenerated because the data has to come
    with it: dropping target_city without copying it would quietly reset
    everyone's location preference to "anywhere", which looks exactly like
    the app forgetting a setting.

    The backfill loops in Python instead of using a JSON function so it runs
    the same on SQLite (local, staging) and Postgres (production, CI) --
    their JSON builtins are not interchangeable.
    """
    op.add_column(
        "users",
        sa.Column("target_cities", sa.JSON(), nullable=False, server_default="[]"),
    )

    conn = op.get_bind()
    rows = conn.execute(sa.text("SELECT id, target_city FROM users")).fetchall()
    for row in rows:
        city = (row.target_city or "").strip()
        conn.execute(
            sa.text("UPDATE users SET target_cities = :cities WHERE id = :id"),
            {"cities": json.dumps([city] if city else []), "id": row.id},
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("target_city")


def downgrade() -> None:
    """Restores the single column, keeping the first city."""
    op.add_column(
        "users",
        sa.Column("target_city", sa.String(length=255), nullable=False, server_default=""),
    )

    conn = op.get_bind()
    rows = conn.execute(sa.text("SELECT id, target_cities FROM users")).fetchall()
    for row in rows:
        raw = row.target_cities
        cities = json.loads(raw) if isinstance(raw, str) else (raw or [])
        conn.execute(
            sa.text("UPDATE users SET target_city = :city WHERE id = :id"),
            {"city": cities[0] if cities else "", "id": row.id},
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("target_cities")
